### ISSUE TITLE
Services with factory still use class constructor

### ISSUE THREAD

**Issue by discordier** [Haehnchen/idea-php-symfony2-plugin-doc#12]
When a service has a factory, the plugin still determines the arguments of the constructor call of the service instance instead of the factory method arguments.
I have the following (simplified):

``` yaml
services:
    dependency:
        class:  Foo\Dependency1
        public: false
    service:
        class:          Foo\Service1
        factory:        [Foo\Factory, create]
# Symfony plugin highlights the following with: "Expect instance of: DateTime"
        arguments:      ["@dependency"]
        public:         true
```

``` php
namespace Foo;

class Foo\Dependency1
{
    public function something()
    {
        return new \DateTime();
    }
}
```

``` php
namespace Foo;

class Foo\Factory
{
    public static function create(Dependency1 $dependency)
    {
        return new Service1($dependency->something());
    }
}
```

``` php
namespace Foo;

class Foo\Service1
{
    public function __construct(\DateTime $data)
    {
        $this->data = $data;
    }
}
```

The symfony plugin should check whether a factory has been defined and if so, examine the arguments of that one.
