### ISSUE TITLE
Missing support for route name_prefix

### ISSUE THREAD

**Issue by nCrazed** [Haehnchen/idea-php-symfony2-plugin-doc#30]
See: https://symfony.com/blog/new-in-symfony-4-1-prefix-imported-route-names

## Example

The following configuration defines a single route named `admin.dashboard`. Referencing the route name triggers "Route Missing" inspections as the plugin thinks that the route name is `dashboard`.
 
```yaml
# config/routes.yaml
admin:
    resource: routes/admin.yaml
    prefix: /admin
    trailing_slash_on_root: false
    name_prefix: admin.
```

```yaml
# config/routes/admin/yaml
dashboard:
    path: /
    controller: App\Admin\Web\DashboardAction
    methods: [GET]
```
