### ISSUE TITLE
Yaml calls doesn't recognize a link to function

### ISSUE THREAD

**Issue by pkly** [Haehnchen/idea-php-symfony2-plugin-doc#40]
When using the following syntax everything works as expected:
```yaml
MyService:
  calls:
    - [myFunction, ['arg1', 'arg2']] // can jump to MyService::myFunction my ctrl+clicking 'myFunction'
```
But the following is also correct in yaml, and symfony recognizes it just fine, but the plugin cannot
```yaml
MyService:
  calls:
    - myFunction: // no link here
      - 'arg1'
      - 'arg2'
```

Using PHPStorm 2020.1.2 and Symfony Support 0.20.196
